import type { Chat, Provider } from './types'

const defaultProviderCatalog: Provider[] = [
  {
    id: 'claude',
    name: 'Claude Code',
    model: null,
    availableModels: [],
    color: '#e5a27f',
    mark: 'AI',
    connected: false,
    installed: null,
    usage: null,
    status: 'Checking Ensync Host…',
    plan: null,
    usageSource: 'unavailable',
    usageKind: 'subscription_quota',
    usageDetails: [],
    resetsIn: null,
    usageReason: 'Waiting for the local Ensync Host.',
    canConnect: false,
    routeKind: 'subscription',
    chatExecution: 'supported',
    setupKind: 'login_command',
    documentationUrl: 'https://code.claude.com/docs/en/installation',
    catalogReason: 'Waiting for Ensync Host capability data.',
    checkedAt: null,
  },
  {
    id: 'codex',
    name: 'Codex',
    model: null,
    availableModels: [],
    color: '#8ee5a1',
    mark: '◎',
    connected: false,
    installed: null,
    usage: null,
    status: 'Checking Ensync Host…',
    plan: null,
    usageSource: 'unavailable',
    usageKind: 'subscription_quota',
    usageDetails: [],
    resetsIn: null,
    usageReason: 'Waiting for the local Ensync Host.',
    canConnect: false,
    routeKind: 'subscription',
    chatExecution: 'supported',
    setupKind: 'login_command',
    documentationUrl: 'https://developers.openai.com/codex/cli/',
    catalogReason: 'Waiting for Ensync Host capability data.',
    checkedAt: null,
  },
  {
    id: 'kimi',
    name: 'Kimi Code',
    model: null,
    availableModels: [],
    color: '#6b8cff',
    mark: 'KM',
    connected: false,
    installed: null,
    usage: null,
    status: 'Checking Ensync Host…',
    plan: null,
    usageSource: 'unavailable',
    usageKind: 'subscription_quota',
    usageDetails: [],
    resetsIn: null,
    usageReason: 'Waiting for the local Ensync Host.',
    canConnect: false,
    routeKind: 'subscription',
    chatExecution: 'discovery_only',
    setupKind: 'login_command',
    documentationUrl: 'https://www.kimi.com/help/kimi-code/cli-getting-started',
    catalogReason: 'Waiting for Ensync Host capability data.',
    checkedAt: null,
  },
  {
    id: 'antigravity',
    name: 'Google Antigravity',
    model: null,
    availableModels: [],
    color: '#5d9eff',
    mark: 'AG',
    connected: false,
    installed: null,
    usage: null,
    status: 'Checking Ensync Host…',
    plan: null,
    usageSource: 'unavailable',
    usageKind: 'subscription_quota',
    usageDetails: [],
    resetsIn: null,
    usageReason: 'Waiting for the local Ensync Host.',
    canConnect: false,
    routeKind: 'subscription',
    chatExecution: 'discovery_only',
    setupKind: 'interactive_onboarding',
    documentationUrl: 'https://antigravity.google/docs/cli/install',
    catalogReason: 'Waiting for Ensync Host capability data.',
    checkedAt: null,
  },
  {
    id: 'jules',
    name: 'Google Jules',
    model: null,
    availableModels: [],
    color: '#4285f4',
    mark: 'JU',
    connected: false,
    installed: null,
    usage: null,
    status: 'Checking Ensync Host…',
    plan: null,
    usageSource: 'unavailable',
    usageKind: 'subscription_quota',
    usageDetails: [],
    resetsIn: null,
    usageReason: 'Waiting for the local Ensync Host.',
    canConnect: false,
    routeKind: 'subscription',
    chatExecution: 'discovery_only',
    setupKind: 'login_command',
    documentationUrl: 'https://jules.google/docs/cli/reference/',
    catalogReason: 'Waiting for Ensync Host capability data.',
    checkedAt: null,
  },
  {
    id: 'copilot',
    name: 'GitHub Copilot CLI',
    model: null,
    availableModels: [],
    color: '#9cc9ff',
    mark: 'GH',
    connected: false,
    installed: null,
    usage: null,
    status: 'Checking Ensync Host…',
    plan: null,
    usageSource: 'unavailable',
    usageKind: 'unavailable',
    usageDetails: [],
    resetsIn: null,
    usageReason: 'Waiting for the local Ensync Host.',
    canConnect: false,
    routeKind: 'subscription',
    chatExecution: 'discovery_only',
    setupKind: 'interactive_onboarding',
    documentationUrl: 'https://docs.github.com/en/copilot/how-tos/copilot-cli/set-up-copilot-cli/install-copilot-cli',
    catalogReason: 'Waiting for Ensync Host capability data.',
    checkedAt: null,
  },
  {
    id: 'cursor',
    name: 'Cursor Agent',
    model: null,
    availableModels: [],
    color: '#c7a8ff',
    mark: '⌁',
    connected: false,
    installed: null,
    usage: null,
    status: 'Checking Ensync Host…',
    plan: null,
    usageSource: 'unavailable',
    usageKind: 'unavailable',
    usageDetails: [],
    resetsIn: null,
    usageReason: 'Waiting for the local Ensync Host.',
    canConnect: false,
    routeKind: 'subscription',
    chatExecution: 'discovery_only',
    setupKind: 'login_command',
    documentationUrl: 'https://docs.cursor.com/en/cli/installation',
    catalogReason: 'Waiting for Ensync Host capability data.',
    checkedAt: null,
  },
  {
    id: 'kiro',
    name: 'Kiro CLI',
    model: null,
    availableModels: [],
    color: '#a7dfc4',
    mark: 'K',
    connected: false,
    installed: null,
    usage: null,
    status: 'Checking Ensync Host…',
    plan: null,
    usageSource: 'unavailable',
    usageKind: 'unavailable',
    usageDetails: [],
    resetsIn: null,
    usageReason: 'Waiting for the local Ensync Host.',
    canConnect: false,
    routeKind: 'subscription',
    chatExecution: 'discovery_only',
    setupKind: 'login_command',
    documentationUrl: 'https://kiro.dev/docs/cli/installation/',
    catalogReason: 'Waiting for Ensync Host capability data.',
    checkedAt: null,
  },
  {
    id: 'qoder',
    name: 'Qoder CLI',
    model: null,
    availableModels: [],
    color: '#ff8a5c',
    mark: 'QD',
    connected: false,
    installed: null,
    usage: null,
    status: 'Checking Ensync Host…',
    plan: null,
    usageSource: 'unavailable',
    usageKind: 'unavailable',
    usageDetails: [],
    resetsIn: null,
    usageReason: 'Waiting for the local Ensync Host.',
    canConnect: false,
    routeKind: 'subscription',
    chatExecution: 'discovery_only',
    setupKind: 'interactive_onboarding',
    documentationUrl: 'https://docs.qoder.com/en/cli/quick-start',
    catalogReason: 'Waiting for Ensync Host capability data.',
    checkedAt: null,
  },
  {
    id: 'codebuddy',
    name: 'CodeBuddy Code',
    model: null,
    availableModels: [],
    color: '#38c7a3',
    mark: 'CB',
    connected: false,
    installed: null,
    usage: null,
    status: 'Checking Ensync Host…',
    plan: null,
    usageSource: 'unavailable',
    usageKind: 'unavailable',
    usageDetails: [],
    resetsIn: null,
    usageReason: 'Waiting for the local Ensync Host.',
    canConnect: false,
    routeKind: 'subscription',
    chatExecution: 'discovery_only',
    setupKind: 'interactive_onboarding',
    documentationUrl: 'https://www.codebuddy.ai/docs/cli/quickstart',
    catalogReason: 'Waiting for Ensync Host capability data.',
    checkedAt: null,
  },
  {
    id: 'droid',
    name: 'Factory Droid',
    model: null,
    availableModels: [],
    color: '#f2b84b',
    mark: 'FD',
    connected: false,
    installed: null,
    usage: null,
    status: 'Checking Ensync Host…',
    plan: null,
    usageSource: 'unavailable',
    usageKind: 'subscription_quota',
    usageDetails: [],
    resetsIn: null,
    usageReason: 'Waiting for the local Ensync Host.',
    canConnect: false,
    routeKind: 'subscription',
    chatExecution: 'discovery_only',
    setupKind: 'interactive_onboarding',
    documentationUrl: 'https://docs.factory.ai/cli/getting-started/quickstart',
    catalogReason: 'Waiting for Ensync Host capability data.',
    checkedAt: null,
  },
  {
    id: 'auggie',
    name: 'Augment Auggie',
    model: null,
    availableModels: [],
    color: '#7f6dff',
    mark: 'AU',
    connected: false,
    installed: null,
    usage: null,
    status: 'Checking Ensync Host…',
    plan: null,
    usageSource: 'unavailable',
    usageKind: 'subscription_quota',
    usageDetails: [],
    resetsIn: null,
    usageReason: 'Waiting for the local Ensync Host.',
    canConnect: false,
    routeKind: 'subscription',
    chatExecution: 'discovery_only',
    setupKind: 'login_command',
    documentationUrl: 'https://docs.augmentcode.com/cli/setup-auggie/install-auggie-cli',
    catalogReason: 'Waiting for Ensync Host capability data.',
    checkedAt: null,
  },
  {
    id: 'amp',
    name: 'Amp',
    model: null,
    availableModels: [],
    color: '#ff5ca8',
    mark: 'AM',
    connected: false,
    installed: null,
    usage: null,
    status: 'Checking Ensync Host…',
    plan: null,
    usageSource: 'unavailable',
    usageKind: 'subscription_quota',
    usageDetails: [],
    resetsIn: null,
    usageReason: 'Waiting for the local Ensync Host.',
    canConnect: false,
    routeKind: 'subscription',
    chatExecution: 'discovery_only',
    setupKind: 'login_command',
    documentationUrl: 'https://ampcode.com/manual',
    catalogReason: 'Waiting for Ensync Host capability data.',
    checkedAt: null,
  },
  {
    id: 'gitlab_duo',
    name: 'GitLab Duo CLI',
    model: null,
    availableModels: [],
    color: '#fc6d26',
    mark: 'GL',
    connected: false,
    installed: null,
    usage: null,
    status: 'Checking Ensync Host…',
    plan: null,
    usageSource: 'unavailable',
    usageKind: 'unavailable',
    usageDetails: [],
    resetsIn: null,
    usageReason: 'Waiting for the local Ensync Host.',
    canConnect: false,
    routeKind: 'subscription',
    chatExecution: 'discovery_only',
    setupKind: 'interactive_onboarding',
    documentationUrl: 'https://docs.gitlab.com/user/gitlab_duo_cli/set_up/',
    catalogReason: 'Waiting for Ensync Host capability data.',
    checkedAt: null,
  },
  {
    id: 'oz',
    name: 'Warp Oz',
    model: null,
    availableModels: [],
    color: '#01a4ff',
    mark: 'OZ',
    connected: false,
    installed: null,
    usage: null,
    status: 'Checking Ensync Host…',
    plan: null,
    usageSource: 'unavailable',
    usageKind: 'subscription_quota',
    usageDetails: [],
    resetsIn: null,
    usageReason: 'Waiting for the local Ensync Host.',
    canConnect: false,
    routeKind: 'subscription',
    chatExecution: 'discovery_only',
    setupKind: 'login_command',
    documentationUrl: 'https://docs.warp.dev/reference/cli',
    catalogReason: 'Waiting for Ensync Host capability data.',
    checkedAt: null,
  },
  {
    id: 'junie',
    name: 'Junie CLI',
    model: null,
    availableModels: [],
    color: '#f5cf70',
    mark: 'J',
    connected: false,
    installed: null,
    usage: null,
    status: 'Checking Ensync Host…',
    plan: null,
    usageSource: 'unavailable',
    usageKind: 'session_only',
    usageDetails: [],
    resetsIn: null,
    usageReason: 'Waiting for the local Ensync Host.',
    canConnect: false,
    routeKind: 'subscription',
    chatExecution: 'discovery_only',
    setupKind: 'interactive_onboarding',
    documentationUrl: 'https://junie.jetbrains.com/docs/junie-cli.html',
    catalogReason: 'Waiting for Ensync Host capability data.',
    checkedAt: null,
  },
  {
    id: 'ollama',
    name: 'Ollama (local)',
    model: null,
    availableModels: [],
    color: '#b8c0cc',
    mark: 'OL',
    connected: false,
    installed: null,
    usage: null,
    status: 'Checking Ensync Host…',
    plan: null,
    usageSource: 'unavailable',
    usageKind: 'local_runtime',
    usageDetails: [],
    resetsIn: null,
    usageReason: 'Waiting for the local Ensync Host.',
    canConnect: false,
    routeKind: 'local',
    chatExecution: 'discovery_only',
    setupKind: 'none',
    documentationUrl: 'https://ollama.com/download',
    catalogReason: 'Waiting for Ensync Host capability data.',
    checkedAt: null,
  },
]

// Keep the offline/loading fallback in the same navigation order returned by
// Ensync Host. This is a recognition heuristic, not a market-share ranking.
const providerNavigationOrder: Provider['id'][] = [
  'droid',
  'codex',
  'claude',
  'copilot',
  'cursor',
  'antigravity',
  'jules',
  'kimi',
  'kiro',
  'junie',
  'gitlab_duo',
  'oz',
  'amp',
  'auggie',
  'qoder',
  'codebuddy',
  'ollama',
]

export const defaultProviders: Provider[] = providerNavigationOrder.map((providerId) => {
  const provider = defaultProviderCatalog.find((candidate) => candidate.id === providerId)
  if (!provider) throw new Error(`Missing default provider definition for ${providerId}.`)
  return { ...provider }
})

export const initialChats: Chat[] = [
  {
    id: 'new-conversation',
    projectId: 'ensync',
    title: 'New conversation',
    subtitle: 'Not started',
    group: 'Today',
    provider: 'claude',
    providerMode: 'auto',
    model: null,
    messages: [],
  },
]
